// 小助手窗口的界面文字：中文 / 日文 / 英文（跟着系统语言，其他语言用英文）。
// 宠物自己说的话（气泡）在 i18n.ts。键必须三种语言一一对应，类型会检查。

import { LANG, type Lang } from './i18n';

const ZH = {
  tabTodo: '待办',
  tabCalendar: '日历',
  tabRemind: '报时与休息',
  todoPlaceholder: '要做什么？回车添加',
  dueTitle: '截止时间（可不填），到点 Clawd 会提醒你',
  add: '添加',
  todoEmpty: '还没有待办。加一条试试，设了截止时间的到点会提醒。',
  done: (n: number) => `已完成 ${n} 项`,
  clearDone: '清除已完成',
  delete: '删除',
  noDue: '设截止时间',
  sources: '日历订阅',
  sourceEmpty: '还没有日历。贴一个 iCal 订阅地址，或者选一个本地 .ics 文件。',
  urlPlaceholder: 'https://…/basic.ics 或 webcal://…',
  subscribe: '订阅',
  pickFile: '选择本地 .ics 文件…',
  refresh: '立即刷新',
  urlHint:
    'Google 日历：设置 → 日历设置 → "iCal 格式的私密地址"；Outlook：设置 → 日历 → 共享日历 → 发布日历 → ICS 链接；飞书、钉钉一般在日历设置的"订阅/导出"里。订阅地址相当于密码，别分享给别人。',
  calSettings: '日历提醒',
  leadMin: '提前提醒',
  refreshMin: '订阅刷新间隔',
  allDayHour: '全天日程在几点提醒',
  minutes: '分钟',
  hour: (h: number) => `${h} 点`,
  upcoming: '接下来 7 天',
  noUpcoming: '接下来 7 天没有日程。',
  waiting: '正在等 Clawd 回应…（宠物没在运行的话，日程和状态显示不出来）',
  statusOk: (n: number, t: string) => `✓ ${n} 个日程 · ${t} 更新`,
  statusLoading: '读取中…',
  statusErr: (e: string) => `✗ ${e}`,
  enabled: '启用',
  file: '本地文件',
  chime: '整点报时',
  chimeFrom: '从',
  chimeTo: '到（含）',
  chimeHint: '只在这段时间里的整点报时。Clawd 会举着铃铛摇，几点就摇几下。',
  rest: '休息提醒',
  workMin: '连续用电脑',
  awayMin: '离开多久算休息过',
  repeatMin: '没休息的话隔多久再提醒',
  active: (m: number) => `现在已经连续用了 ${m} 分钟。`,
  tryIt: '试一下',
  testChime: '报时',
  testRest: '休息',
  testEvent: '日程',
  testTodo: '待办',
  saved: '已保存',
  saveFailed: (e: string) => `保存失败：${e}`,
  pickUnavailable: '浏览器预览里不能选本地文件',
  badUrl: '要以 http://、https:// 或 webcal:// 开头',
  allDay: '全天',
  ccLink: '和 Claude Code 联动',
  ccOn: '已开启：Claude Code 在干什么，Clawd 就跟着做什么。',
  ccOff: '未开启。开启后 Clawd 会跟着 Claude Code 思考、敲电脑、庆祝……',
  ccStale: 'hooks 指向的程序位置不对（换过安装位置？），点「重新开启」修好。',
  ccLast: (ago: string) => `上次收到 Claude Code 的消息：${ago}`,
  ccNever: '还没收到过 Claude Code 的消息。',
  ccEnable: '开启联动',
  ccDisable: '关闭联动',
  ccReinstall: '重新开启',
  ccPermission:
    '在气泡上批准权限请求（Claude 要跑命令、改文件时，Clawd 跑过去敲窗口，你可以直接在气泡上点允许 / 拒绝）',
  ccHint: (path: string) =>
    `开启会往 ${path} 的 hooks 里加几条，都指向本程序；关闭时会删掉，不动你自己的 hooks。第一次改之前会备份成 settings.json.clawd-backup。已经开着的 Claude Code 会话也会生效。`,
  ccReactions: 'Clawd 的反应',
  ccCelebrate: '一轮干完：后空翻撒彩纸',
  ccDoneBubble: '干了半分钟以上才完成：冒个气泡告诉你',
  ccZap: '出错：被电一下',
  ccMinis: '派出子代理：掉下来一只迷你 Clawd 帮忙',
  ccSessions: '正在联动的会话',
  ccNoSessions: '没有。在 Claude Code 里发一句话试试。',
  ccMood: { idle: '空闲', thinking: '思考中', working: '干活中', compacting: '整理上下文' } as Record<string, string>,
  ccSubagents: (n: number) => ` · ${n} 个子代理`,
  ccTestThink: '思考',
  ccTestWork: '干活',
  ccTestSub: '子代理',
  ccTestCompact: '压缩上下文',
  ccTestError: '出错',
  ccTestPerm: '权限请求',
  ccTestDone: '完成',
  ccTestHint: '模拟 Claude Code 的事件，看看 Clawd 的反应（不会真的影响 Claude Code）。',
  ago: (s: number) => (s < 60 ? `${s} 秒前` : s < 3600 ? `${Math.floor(s / 60)} 分钟前` : `${Math.floor(s / 3600)} 小时前`),
};

const EN: typeof ZH = {
  tabTodo: 'To-dos',
  tabCalendar: 'Calendar',
  tabRemind: 'Chime & breaks',
  todoPlaceholder: 'What needs doing? Press Enter to add',
  dueTitle: 'Due time (optional). Clawd reminds you when it is due',
  add: 'Add',
  todoEmpty: 'No to-dos yet. Give one a due time and Clawd will remind you.',
  done: (n: number) => `${n} completed`,
  clearDone: 'Clear completed',
  delete: 'Delete',
  noDue: 'Set due time',
  sources: 'Calendar subscriptions',
  sourceEmpty: 'No calendars yet. Paste an iCal subscription link or choose a local .ics file.',
  urlPlaceholder: 'https://…/basic.ics or webcal://…',
  subscribe: 'Subscribe',
  pickFile: 'Choose a local .ics file…',
  refresh: 'Refresh now',
  urlHint:
    'Google Calendar: Settings → your calendar → "Secret address in iCal format". Outlook: Settings → Calendar → Shared calendars → Publish a calendar → ICS link. Treat the link like a password.',
  calSettings: 'Calendar reminders',
  leadMin: 'Remind me',
  refreshMin: 'Refresh every',
  allDayHour: 'All-day events at',
  minutes: 'min',
  hour: (h: number) => `${h}:00`,
  upcoming: 'Next 7 days',
  noUpcoming: 'Nothing in the next 7 days.',
  waiting: 'Waiting for Clawd… (events and status show up while the pet is running)',
  statusOk: (n: number, t: string) => `✓ ${n} events · updated ${t}`,
  statusLoading: 'Loading…',
  statusErr: (e: string) => `✗ ${e}`,
  enabled: 'Enabled',
  file: 'Local file',
  chime: 'Hourly chime',
  chimeFrom: 'From',
  chimeTo: 'To (inclusive)',
  chimeHint: 'Chimes only on the hour within this range. Clawd rings a bell once per hour on the clock.',
  rest: 'Break reminders',
  workMin: 'After using the computer for',
  awayMin: 'Counts as a break after',
  repeatMin: 'If no break, remind again after',
  active: (m: number) => `You've been at it for ${m} minutes.`,
  tryIt: 'Try it',
  testChime: 'Chime',
  testRest: 'Break',
  testEvent: 'Event',
  testTodo: 'To-do',
  saved: 'Saved',
  saveFailed: (e: string) => `Save failed: ${e}`,
  pickUnavailable: 'Local files are not available in the browser preview',
  badUrl: 'Must start with http://, https:// or webcal://',
  allDay: 'All day',
  ccLink: 'Link with Claude Code',
  ccOn: 'On: whatever Claude Code is doing, Clawd follows along.',
  ccOff: 'Off. Turn it on and Clawd thinks, types, and celebrates along with Claude Code.',
  ccStale: 'The hooks point to an old location of this app. Click "Reconnect" to fix them.',
  ccLast: (ago: string) => `Last message from Claude Code: ${ago}`,
  ccNever: 'No messages from Claude Code yet.',
  ccEnable: 'Turn on',
  ccDisable: 'Turn off',
  ccReinstall: 'Reconnect',
  ccPermission:
    'Approve permission requests from the bubble (when Claude wants to run a command or edit a file, Clawd knocks on its window and you can click Allow / Deny)',
  ccHint: (path: string) =>
    `Turning this on adds a few hooks to ${path}, all pointing at this app. Turning it off removes them and leaves your own hooks alone. The file is backed up to settings.json.clawd-backup before the first change. Sessions that are already open pick it up too.`,
  ccReactions: "Clawd's reactions",
  ccCelebrate: 'Turn finished: backflip and confetti',
  ccDoneBubble: 'Finished after more than 30 s: show a bubble',
  ccZap: 'Error: get zapped',
  ccMinis: 'Subagent started: a mini Clawd drops in to help',
  ccSessions: 'Linked sessions',
  ccNoSessions: 'None yet. Send Claude Code a message.',
  ccMood: { idle: 'idle', thinking: 'thinking', working: 'working', compacting: 'compacting' } as Record<string, string>,
  ccSubagents: (n: number) => ` · ${n} subagent${n === 1 ? '' : 's'}`,
  ccTestThink: 'Thinking',
  ccTestWork: 'Working',
  ccTestSub: 'Subagent',
  ccTestCompact: 'Compact',
  ccTestError: 'Error',
  ccTestPerm: 'Permission',
  ccTestDone: 'Done',
  ccTestHint: "Simulates Claude Code events to preview Clawd's reactions. Claude Code itself isn't affected.",
  ago: (s: number) => (s < 60 ? `${s}s ago` : s < 3600 ? `${Math.floor(s / 60)} min ago` : `${Math.floor(s / 3600)} h ago`),
};

// 日本語：設定項目・エラーは丁寧語。Clawd が話しかける部分（空の状態や補足）だけ、大阪の蟹らしく関西弁。
const JA: typeof ZH = {
  tabTodo: 'ToDo',
  tabCalendar: 'カレンダー',
  tabRemind: '時報と休憩',
  todoPlaceholder: 'やることを入力（Enterで追加）',
  dueTitle: '期限（省略可）。時間になったらClawdが教えるで',
  add: '追加',
  todoEmpty: 'ToDoはまだ空っぽやで。期限を付けといたら、時間になったら教えたるわ。',
  done: (n: number) => `完了 ${n}件`,
  clearDone: '完了分を削除',
  delete: '削除',
  noDue: '期限を設定',
  sources: 'カレンダーの購読',
  sourceEmpty: 'カレンダーがまだないで。iCalの購読URLを貼るか、ローカルの.icsファイルを選んでな。',
  urlPlaceholder: 'https://…/basic.ics または webcal://…',
  subscribe: '購読',
  pickFile: 'ローカルの.icsファイルを選択…',
  refresh: '今すぐ更新',
  urlHint:
    'Googleカレンダー：設定 → 対象のカレンダー →「iCal形式の非公開URL」。Outlook：設定 → カレンダー → 共有カレンダー → カレンダーを公開 → ICSリンク。購読URLはパスワードと同じです。他の人に共有しないでください。',
  calSettings: 'カレンダーの通知',
  leadMin: '何分前に通知',
  refreshMin: '購読の更新間隔',
  allDayHour: '終日の予定を通知する時刻',
  minutes: '分',
  hour: (h: number) => `${h}時`,
  upcoming: '今後7日間',
  noUpcoming: '今後7日間の予定はないで。',
  waiting: 'Clawdの返事待ちやで…（ペットが起動してへんと、予定や状態は出てこうへんで）',
  statusOk: (n: number, t: string) => `✓ ${n}件の予定 · ${t}に更新`,
  statusLoading: '読み込み中…',
  statusErr: (e: string) => `✗ ${e}`,
  enabled: '有効',
  file: 'ローカルファイル',
  chime: '時報',
  chimeFrom: '開始',
  chimeTo: '終了（含む）',
  chimeHint: 'この時間帯の正時だけ鳴らすで。Clawdがベルを持って、何時かの数だけ鳴らすんや。',
  rest: '休憩の通知',
  workMin: '連続使用時間',
  awayMin: '何分離れたら休憩したことにする',
  repeatMin: '休憩しなかったときの再通知間隔',
  active: (m: number) => `今、${m}分連続で使ってるで。`,
  tryIt: '試してみる',
  testChime: '時報',
  testRest: '休憩',
  testEvent: '予定',
  testTodo: 'ToDo',
  saved: '保存しました',
  saveFailed: (e: string) => `保存に失敗しました：${e}`,
  pickUnavailable: 'ブラウザのプレビューではローカルファイルを選べません',
  badUrl: 'http://、https://、webcal:// のいずれかで始めてください',
  allDay: '終日',
  ccLink: 'Claude Codeと連携',
  ccOn: 'オン：Claude Codeが何してても、Clawdが一緒に動くで。',
  ccOff: 'オフ。オンにしたら、Clawdが Claude Codeと一緒に考えたり、キーボード叩いたり、お祝いしたりするで。',
  ccStale: 'hooksが指しているアプリの場所が古くなっています（インストール先を変更しましたか？）。「再接続」を押して直してください。',
  ccLast: (ago: string) => `Claude Codeからの最終受信：${ago}`,
  ccNever: 'Claude Codeからはまだ何も届いてへんで。',
  ccEnable: '連携をオンにする',
  ccDisable: '連携をオフにする',
  ccReinstall: '再接続',
  ccPermission:
    '吹き出しで権限リクエストを承認する（Claudeがコマンドの実行やファイルの編集をしようとすると、Clawdが走っていってウィンドウをノックします。吹き出しの「許可」「拒否」を押せます）',
  ccHint: (path: string) =>
    `オンにすると、${path} のhooksにこのアプリを指す項目をいくつか追加します。オフにすると削除し、ご自身のhooksには触れません。最初に変更する前に settings.json.clawd-backup としてバックアップします。すでに開いているClaude Codeのセッションにも反映されます。`,
  ccReactions: 'Clawdのリアクション',
  ccCelebrate: '1ターン完了：バク宙して紙吹雪',
  ccDoneBubble: '30秒以上かかった作業が終わったら、吹き出しで知らせる',
  ccZap: 'エラー：ビリビリ感電',
  ccMinis: 'サブエージェント起動：ミニClawdが手伝いに降ってくる',
  ccSessions: '連携中のセッション',
  ccNoSessions: 'まだないで。Claude Codeに一言送ってみてな。',
  ccMood: { idle: '待機中', thinking: '考え中', working: '作業中', compacting: 'コンテキスト整理中' } as Record<string, string>,
  ccSubagents: (n: number) => ` · サブエージェント${n}個`,
  ccTestThink: '考え中',
  ccTestWork: '作業',
  ccTestSub: 'サブエージェント',
  ccTestCompact: '圧縮',
  ccTestError: 'エラー',
  ccTestPerm: '権限',
  ccTestDone: '完了',
  ccTestHint: 'Claude Codeのイベントを模擬して、Clawdの反応を確かめます（Claude Code本体には影響しません）。',
  ago: (s: number) => (s < 60 ? `${s}秒前` : s < 3600 ? `${Math.floor(s / 60)}分前` : `${Math.floor(s / 3600)}時間前`),
};

/** 三种语言的完整表（类型保证键一一对应）和当前语言的那一份 */
export const STRINGS: Record<Lang, typeof ZH> = { zh: ZH, ja: JA, en: EN };
export const W = STRINGS[LANG];
